import io
import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Font Configuration (Indic Unicode Support) ──
font_name = 'Helvetica'
font_bold_name = 'Helvetica-Bold'

# Try Windows font first, then Linux fallbacks
font_paths = [
    "C:\\Windows\\Fonts\\Nirmala.ttc",                         # Windows
    "/usr/share/fonts/truetype/nirmala/Nirmala.ttf",          # Linux
    "/usr/share/fonts/truetype/freefont/FreeSans.ttf",        # Linux fallback
]
for font_path in font_paths:
    if os.path.exists(font_path):
        try:
            pdfmetrics.registerFont(TTFont('CustomFont', font_path))
            pdfmetrics.registerFont(TTFont('CustomFont-Bold', font_path))
            font_name = 'CustomFont'
            font_bold_name = 'CustomFont'
            print(f"ReportLab: Registered font from {font_path}")
            break
        except Exception as e:
            print(f"ReportLab: Font load failed ({font_path}): {e}")
            continue


# ── Translation Dictionaries for PDF Reports ──
SYMPTOM_PDF_TRANSLATIONS = {
    "English": {
        "report_title": "MediMitra AI Health Report",
        "report_subtitle": "Symptom Check Analysis Report",
        "condition_name": "Condition Name:",
        "severity_level": "Severity Level:",
        "ai_confidence": "AI Confidence:",
        "clinical_explanation": "Clinical Explanation",
        "home_remedies": "Recommended Home Remedies",
        "red_flags": "Red Flags / Warning Signs",
        "disclaimer_title": "Medical Disclaimer:",
        "disclaimer_body": "This report is generated by an artificial intelligence assistant for educational and informational purposes only. It does NOT constitute medical advice, diagnosis, or treatment. Always consult a licensed healthcare professional for any medical concerns or emergency situations."
    },
    "Hindi": {
        "report_title": "MediMitra AI स्वास्थ्य रिपोर्ट",
        "report_subtitle": "लक्षण जांच विश्लेषण रिपोर्ट",
        "condition_name": "संभावित स्थिति:",
        "severity_level": "गंभीरता का स्तर:",
        "ai_confidence": "AI का विश्वास:",
        "clinical_explanation": "चिकित्सीय व्याख्या",
        "home_remedies": "सुझाए गए घरेलू उपचार",
        "red_flags": "चेतावनी संकेत / खतरे के लक्षण",
        "disclaimer_title": "चिकित्सीय अस्वीकरण:",
        "disclaimer_body": "यह रिपोर्ट केवल शैक्षिक और सूचनात्मक उद्देश्यों के लिए एक कृत्रिम बुद्धिमत्ता सहायक द्वारा उत्पन्न की गई है। यह पेशेवर चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है। हमेशा चिकित्सा निर्णयों के लिए डॉक्टर से परामर्श करें।"
    },
    "Odia": {
        "report_title": "MediMitra AI ସ୍ୱାସ୍ଥ୍ୟ ରିପୋର୍ଟ",
        "report_subtitle": "ଲକ୍ଷଣ ଯାଞ୍ଚ ବିଶ୍ଳେଷଣ ରିପୋର୍ଟ",
        "condition_name": "ସମ୍ଭାବ୍ୟ ରୋଗ:",
        "severity_level": "ଗୁରୁତରତା:",
        "ai_confidence": "AI ବିଶ୍ୱାସନୀୟତା:",
        "clinical_explanation": "ଚିକିତ୍ସା ସମ୍ବନ୍ଧୀୟ ବ୍ୟାଖ୍ୟା",
        "home_remedies": "ଘରୋଇ ଉପଚାର",
        "red_flags": "ବିପଦ ସଙ୍କେତ",
        "disclaimer_title": "ଚିକିତ୍ସା ଦାବିତ୍ୟାଗ:",
        "disclaimer_body": "ଏହି ରିପୋର୍ଟ କେବଳ ଶିକ୍ଷାଗତ ଏବଂ ସୂଚନା ପ୍ରଦାନ ଉଦ୍ଦେଶ୍ୟରେ AI ସହାୟକ ଦ୍ୱାରା ପ୍ରସ୍ତուତ କରାଯାଇଛି। ଏହା ବୃତ୍ତିଗତ ଚିକିତ୍ସା ପରାମର୍ଶର ବିକଳ୍ପ ନୁହେଁ। ଯେକୌଣସି ଚିକିତ୍ସା ନିଷ୍ପତ୍ତି ପାଇଁ ସର୍ବଦା ଡାକ୍තରଙ୍କ ସହ ପରାମର୍ଶ କରନ୍ତୁ।"
    },
    "Bengali": {
        "report_title": "MediMitra AI স্বাস্থ্য রিপোর্ট",
        "report_subtitle": "লক্ষণ পরীক্ষা বিশ্লেষণ রিপোর্ট",
        "condition_name": "সম্ভাব্য রোগ:",
        "severity_level": "তীব্রতা:",
        "ai_confidence": "AI বিশ্বাসযোগ্যতা:",
        "clinical_explanation": "চিকিৎসা সংক্রান্ত ব্যাখ্যা",
        "home_remedies": "ঘরোয়া প্রতিকার",
        "red_flags": "সতর্কতা সংকেত",
        "disclaimer_title": "চিকিৎসা দাবিত্যাগ:",
        "disclaimer_body": "এই রিপোর্টটি শুধুমাত্র শিক্ষামূলক ও তথ্যগত উদ্দেশ্যে একটি কৃত্রিম বুদ্ধিমত্তা সহকারী দ্বারা তৈরি করা হয়েছে। এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়। সর্বদা ডাক্তারের পরামর্শ নিন।"
    },
    "Tamil": {
        "report_title": "MediMitra AI சுகாதார அறிக்கை",
        "report_subtitle": "அறிகுறி சோதனை பகுப்பாய்வு அறிக்கை",
        "condition_name": "சாத்தியமான பாதிப்பு:",
        "severity_level": "தீவிரம்:",
        "ai_confidence": "AI நம்பிக்கை அளவு:",
        "clinical_explanation": "மருத்துவ விளக்கம்",
        "home_remedies": "பரிந்துரைக்கப்பட்ட வீட்டு வைத்தியம்",
        "red_flags": "எச்சரிக்கை அறிகுறிகள்",
        "disclaimer_title": "மருத்துவ மறுப்பு:",
        "disclaimer_body": "இந்த அறிக்கை கல்வி மற்றும் தகவல் நோக்கங்களுக்காக மட்டுமே ஒரு செயற்கை நுண்ணறிவு உதவியாளரால் உருவாக்கப்பட்டது. இது தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாகாது."
    },
    "Telugu": {
        "report_title": "MediMitra AI ఆరోగ్య నివేదిక",
        "report_subtitle": "లక్షణ తనిఖీ విశ్లేషణ నివేదిక",
        "condition_name": "సాధ్యమయ్యే పరిస్థితి:",
        "severity_level": "తీవ్రత స్థాయి:",
        "ai_confidence": "AI విశ్వాసం:",
        "clinical_explanation": "వైద్య వివరణ",
        "home_remedies": "గృహ చిట్కాలు",
        "red_flags": "హెచ్చరిక సంకేతాలు",
        "disclaimer_title": "వైద్య నిరాకరణ:",
        "disclaimer_body": "ఈ నివేదిక కేవలం విద్యా మరియు సమాచార ప్రయోజనాల కోసం AI సహాయకుడి ద్వారా రూపొందించబడింది. ఇది వృత్తిపరమైన వైద్య సలహాకు ప్రత్యామ్నాయం కాదు."
    },
    "Marathi": {
        "report_title": "MediMitra AI आरोग्य अहवाल",
        "report_subtitle": "लक्षण तपासणी विश्लेषण अहवाल",
        "condition_name": "संभाव्य आजार:",
        "severity_level": "तीव्रता:",
        "ai_confidence": "AI विश्वास:",
        "clinical_explanation": "वैद्यकीय स्पष्टीकरण",
        "home_remedies": "घरगुती उपचार",
        "red_flags": "धोक्याचे इशारे",
        "disclaimer_title": "वैद्यकीय अस्वीकरण:",
        "disclaimer_body": "हा अहवाल केवळ शैक्षणिक आणि माहितीच्या उद्देशाने कृत्रिम बुद्धिमत्ता सहाय्यकाद्वारे तयार केला गेला आहे. हा व्यावसायिक वैद्यकीय सल्ल्याचा पर्याय नाही।"
    }
}

LIFESTYLE_PDF_TRANSLATIONS = {
    "English": {
        "report_title": "MediMitra Health Advisor",
        "report_subtitle": "Personalized 7-Day Lifestyle & Wellness Plan",
        "your_bmi": "Your BMI:",
        "morning_routine": "🌅 Morning Routine",
        "wake_time": "Wake Time:",
        "drink": "Drink:",
        "activity": "Activity:",
        "meals_diet": "🍽️ Meals & Diet",
        "breakfast": "Breakfast:",
        "snack": "Snack:",
        "lunch": "Lunch:",
        "dinner": "Dinner:",
        "total_calories": "Total Calories:",
        "exercise_activity": "🏃 Exercise & Activity",
        "type": "Type:",
        "duration": "Duration:",
        "intensity": "Intensity:",
        "routine": "Routine:",
        "wellness_sleep": "💧 Wellness & Sleep",
        "water_intake": "Water Intake:",
        "sleep": "Sleep:",
        "tip": "Tip:",
        "disclaimer": "Disclaimer: This plan is generated by an artificial intelligence helper. Please consult your physical trainer or doctor before undertaking any new workout or diet regimen."
    },
    "Hindi": {
        "report_title": "MediMitra स्वास्थ्य सलाहकार",
        "report_subtitle": "व्यक्तिगत 7-दिवसीय जीवनशैली और कल्याण योजना",
        "your_bmi": "आपका BMI:",
        "morning_routine": "🌅 सुबह की दिनचर्या",
        "wake_time": "उठने का समय:",
        "drink": "पेय:",
        "activity": "गतिविधि:",
        "meals_diet": "🍽️ भोजन और आहार",
        "breakfast": "नाश्ता:",
        "snack": "अल्पाहार:",
        "lunch": "दोपहर का भोजन:",
        "dinner": "रात का भोजन:",
        "total_calories": "कुल कैलोरी:",
        "exercise_activity": "🏃 व्यायाम और गतिविधि",
        "type": "प्रकार:",
        "duration": "अवधि:",
        "intensity": "तीव्रता:",
        "routine": "नियमित गतिविधि:",
        "wellness_sleep": "💧 कल्याण और नींद",
        "water_intake": "पानी का सेवन:",
        "sleep": "नींद:",
        "tip": "सुझाव:",
        "disclaimer": "अस्वीकरण: यह योजना कृत्रिम बुद्धिमत्ता सहायक द्वारा तैयार की गई है। कृपया कोई भी नया वर्कआउट या आहार शुरू करने से पहले अपने डॉक्टर या ट्रेनर से सलाह लें।"
    },
    "Odia": {
        "report_title": "MediMitra ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶଦାତା",
        "report_subtitle": "ବ୍ୟକ୍ତିଗତ 7-ଦିନର ଜୀବନଶୈଳୀ ଏବଂ କଲ୍ୟାଣ ଯୋଜନା",
        "your_bmi": "ଆପଣଙ୍କ BMI:",
        "morning_routine": "🌅 ସକାଳର ନିତ୍ୟକର୍ମ",
        "wake_time": "ଉଠିବା ସମୟ:",
        "drink": "ପେୟ:",
        "activity": "କାର୍ଯ୍ୟକଳାପ:",
        "meals_diet": "🍽️ ଭୋଜନ ଏବଂ ଆହାର",
        "breakfast": "ଜଳଖିଆ:",
        "snack": "ଜଳଖିଆ:",
        "lunch": "ମଧ୍ୟାହ୍ନ ଭୋଜନ:",
        "dinner": "ରାତ୍ରି ଭୋଜନ:",
        "total_calories": "ମୋଟ କ୍ୟାଲୋରୀ:",
        "exercise_activity": "🏃 ବ୍ୟାୟାମ ଏବଂ କାର୍ଯ୍ୟକଳାପ",
        "type": "ପ୍ରକାର:",
        "duration": "ଅବଧି:",
        "intensity": "ତୀବ୍ରତା:",
        "routine": "ନିୟମିତ ବ୍ୟାୟାମ:",
        "wellness_sleep": "💧 ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ନିଦ୍ରା",
        "water_intake": "ପାଣି ପିଇବା:",
        "sleep": "ନିଦ୍ରା:",
        "tip": "ଟିପ୍ସ:",
        "disclaimer": "ଦାବିତ୍ୟାଗ: ଏହି ଯୋଜନା AI ସହାୟକ ଦ୍ୱାରା ପ୍ରସ୍ତୁତ କରାଯାଇଛି। କୌଣସି ନୂତନ ବ୍ୟାୟାମ କିମ୍ବା ଆହାର ଆରମ୍ଭ କରିବା ପୂର୍ବରୁ ଡାକ୍ତରଙ୍କ ସରାହ ନିଅନ୍ତୁ।"
    },
    "Bengali": {
        "report_title": "MediMitra স্বাস্থ্য উপদেষ্টা",
        "report_subtitle": "ব্যক্তিগত ৭-দিনের জীবনধারা এবং সুস্থতা পরিকল্পনা",
        "your_bmi": "আপনার BMI:",
        "morning_routine": "🌅 সকালের রুটিন",
        "wake_time": "ঘুম থেকে ওঠার সময়:",
        "drink": "পানীয়:",
        "activity": "ক্রিয়াকলাপ:",
        "meals_diet": "🍽️ খাবার ও ডায়েট",
        "breakfast": "প্রাতঃরাশ:",
        "snack": "নাশতা:",
        "lunch": "দুপুরের খাবার:",
        "dinner": "রাতের খাবার:",
        "total_calories": "মোট ক্যালোরি:",
        "exercise_activity": "🏃 ব্যায়াম ও ক্রিয়াকলাপ",
        "type": "ধরন:",
        "duration": "সময়কাল:",
        "intensity": "তীব্রতা:",
        "routine": "ব্যায়ামের রুটিন:",
        "wellness_sleep": "💧 সুস্থতা ও ঘুম",
        "water_intake": "জল খাওয়া:",
        "sleep": "ঘুম:",
        "tip": "পরামর্শ:",
        "disclaimer": "দাবিত্যাগ: এই পরিকল্পনাটি কৃত্রিম বুদ্ধিমত্তা সহকারী দ্বারা তৈরি করা হয়েছে। কোনো নতুন ওয়ার্কআউট বা ডায়েট শুরু করার আগে আপনার ডাক্তারের পরামর্শ নিন।"
    },
    "Tamil": {
        "report_title": "MediMitra சுகாதார ஆலோசகர்",
        "report_subtitle": "தனிப்பயனாக்கப்பட்ட 7-நாள் வாழ்க்கை முறை மற்றும் உடலநலத் திட்டம்",
        "your_bmi": "உங்கள் BMI:",
        "morning_routine": "🌅 காலை வழக்கம்",
        "wake_time": "எழும்பும் நேரம்:",
        "drink": "பானம்:",
        "activity": "செயல்பாடு:",
        "meals_diet": "🍽️ உணவுத் திட்டம்",
        "breakfast": "காலை உணவு:",
        "snack": "சிற்றுண்டி:",
        "lunch": "மதிய உணவு:",
        "dinner": "இரவு உணவு:",
        "total_calories": "மொத்த கலோரிகள்:",
        "exercise_activity": "🏃 உடற்பயிற்சி மற்றும் செயல்பாடு",
        "type": "வகை:",
        "duration": "நேரம்:",
        "intensity": "தீவிரம்:",
        "routine": "உடற்பயிற்சி வழக்கம்:",
        "wellness_sleep": "💧 நல்வாழ்வு மற்றும் தூக்கம்",
        "water_intake": "நீர் உட்கொள்ளல்:",
        "sleep": "தூக்கம்:",
        "tip": "குறிப்பு:",
        "disclaimer": "மறுப்பு: இந்த திட்டம் AI உதவியாளரால் உருவாக்கப்பட்டது. புதிய உடற்பயிற்சி அல்லது உணவுத் திட்டத்தைத் தொடங்குவதற்கு முன் மருத்துவரை அணுகவும்."
    },
    "Telugu": {
        "report_title": "MediMitra ఆరోగ్య సలహాదారు",
        "report_subtitle": "వ్యక్తిగతీకరించిన 7-రోజుల జీవనశైలి & ఆరోగ్య ప్రణాళిక",
        "your_bmi": "మీ BMI:",
        "morning_routine": "🌅 ఉదయపు దినచర్య",
        "wake_time": "నిద్ర లేచే సమయం:",
        "drink": "పానీయం:",
        "activity": "కార్యకలాపం:",
        "meals_diet": "🍽️ భోజన ప్రణాళిక",
        "breakfast": "అల్పాహారం:",
        "snack": "స్నాక్స్:",
        "lunch": "మధ్యాహ్న భోజనం:",
        "dinner": "రాత్రి భోజనం:",
        "total_calories": "మొత్తం కేలరీలు:",
        "exercise_activity": "🏃 వ్యాయామం & యాక్టివిటీ",
        "type": "రకం:",
        "duration": "వ్యవధి:",
        "intensity": "తీవ్రత:",
        "routine": "వ్యాయామ దినచర్య:",
        "wellness_sleep": "💧 ఆరోగ్యం & నిద్ర",
        "water_intake": "నీటి వినియోగం:",
        "sleep": "నిద్ర:",
        "tip": "చిట్కా:",
        "disclaimer": "నిరాకరణ: ఈ ప్రణాళిక AI సహాయకుడి ద్వారా రూపొందించబడింది. ఏదైనా కొత్త వ్యాయామం లేదా ఆహారం ప్రారంభించే ముందు మీ వైద్యుడిని సంప్రదించండి."
    },
    "Marathi": {
        "report_title": "MediMitra आरोग्य सल्लागार",
        "report_subtitle": "वैयक्तिक ७-दिवसीय जीवनशैली आणि कल्याण योजना",
        "your_bmi": "तुमचा BMI:",
        "morning_routine": "🌅 सकाळची दिनचर्या",
        "wake_time": "उठण्याची वेळ:",
        "drink": "पेय:",
        "activity": "कृती:",
        "meals_diet": "🍽️ भोजन आणि आहार",
        "breakfast": "नाश्ता:",
        "snack": "अल्पाहार:",
        "lunch": "दुपारचे जेवण:",
        "dinner": "रात्रीचे जेवण:",
        "total_calories": "एकूण कॅलरी:",
        "exercise_activity": "🏃 व्यायाम आणि कृती",
        "type": "प्रकार:",
        "duration": "कालावधी:",
        "intensity": "तीव्रता:",
        "routine": "नियमित व्यायाम:",
        "wellness_sleep": "💧 कल्याण आणि झोप",
        "water_intake": "पाण्याचे सेवन:",
        "sleep": "झोप:",
        "tip": "टीप:",
        "disclaimer": "अस्वीकरण: ही योजना कृत्रिम बुद्धिमत्ता सहाय्यकाद्वारे तयार करण्यात आली आहे. नवीन व्यायाम किंवा आहार सुरू करण्यापूर्वी कृपया डॉक्टरांचा सल्ला घ्या।"
    }
}


def generate_symptom_pdf(data: dict) -> bytes:
    """
    Generate a beautifully formatted, branded PDF for symptom check results.
    Supports Unicode Indic scripts.
    """
    lang = data.get("language", "English")
    dict_labels = SYMPTOM_PDF_TRANSLATIONS.get(lang, SYMPTOM_PDF_TRANSLATIONS["English"])

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()
    
    # Custom Styles
    primary_color = colors.HexColor("#1A7A4A")
    text_color = colors.HexColor("#1E293B")
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=font_bold_name,
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=15
    )
    
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName=font_bold_name,
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0D9488"),
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName=font_name,
        fontSize=10.5,
        leading=15,
        textColor=text_color,
        spaceAfter=8
    )

    bullet_style = ParagraphStyle(
        'BulletCustom',
        parent=body_style,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )

    story = []
    
    # Header Branding
    story.append(Paragraph(dict_labels["report_title"], title_style))
    story.append(Paragraph(f"<b>{dict_labels['report_subtitle']}</b>", ParagraphStyle('SubTitle', fontName=font_bold_name, fontSize=12, leading=14, textColor=colors.HexColor("#64748B"), spaceAfter=15)))
    
    # Decorative line
    divider = Table([[""]], colWidths=[504])
    divider.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 1.5, primary_color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(divider)
    story.append(Spacer(1, 15))
    
    # Summary Details Table
    severity = data.get("severity", "Mild")
    severity_colors = {"Severe": "#DC2626", "Moderate": "#D97706", "Mild": "#16A34A",
                       "गंभीर": "#DC2626", "मध्यम": "#D97706", "हल्का": "#16A34A"}
    sev_color = severity_colors.get(severity, "#16A34A")
    
    summary_data = [
        [Paragraph(f"<b>{dict_labels['condition_name']}</b>", body_style), Paragraph(f"{data.get('condition', 'N/A')}", body_style)],
        [Paragraph(f"<b>{dict_labels['severity_level']}</b>", body_style), Paragraph(f"<font color='{sev_color}'><b>{severity}</b></font>", body_style)],
        [Paragraph(f"<b>{dict_labels['ai_confidence']}</b>", body_style), Paragraph(f"{data.get('confidence', 0)}%", body_style)]
    ]
    
    summary_table = Table(summary_data, colWidths=[140, 364])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 15))
    
    # Explanation Section
    story.append(Paragraph(dict_labels["clinical_explanation"], section_style))
    story.append(Paragraph(data.get("explanation", "No explanation available."), body_style))
    story.append(Spacer(1, 10))
    
    # Home Remedies Section
    story.append(Paragraph(dict_labels["home_remedies"], section_style))
    for remedy in data.get("home_remedies", []):
        story.append(Paragraph(f"• {remedy}", bullet_style))
    story.append(Spacer(1, 10))
    
    # Red Flags Section
    story.append(Paragraph(dict_labels["red_flags"], section_style))
    warning_style = ParagraphStyle(
        'WarningText',
        parent=bullet_style,
        textColor=colors.HexColor("#DC2626")
    )
    for flag in data.get("red_flags", []):
        story.append(Paragraph(f"⚠️ {flag}", warning_style))
    story.append(Spacer(1, 20))
    
    # Disclaimer block
    disclaimer_text = (
        f"<b>{dict_labels['disclaimer_title']}</b> {dict_labels['disclaimer_body']}"
    )
    disclaimer_table = Table([[Paragraph(disclaimer_text, ParagraphStyle('Disclaimer', parent=body_style, fontSize=8.5, leading=12, textColor=colors.HexColor("#64748B")))]], colWidths=[504])
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FEF2F2")),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#FCA5A5")),
        ('PADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(disclaimer_table)
    
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def generate_lifestyle_pdf(data: dict) -> bytes:
    """
    Generate a beautifully formatted, multi-page branded PDF for a 7-day lifestyle plan.
    Supports Unicode Indic scripts.
    """
    lang = data.get("language", "English")
    dict_labels = LIFESTYLE_PDF_TRANSLATIONS.get(lang, LIFESTYLE_PDF_TRANSLATIONS["English"])

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()
    
    primary_color = colors.HexColor("#1A7A4A")
    accent_color = colors.HexColor("#0D9488")
    text_color = colors.HexColor("#1E293B")
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName=font_bold_name,
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=5
    )
    
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName=font_bold_name,
        fontSize=15,
        leading=19,
        textColor=accent_color,
        spaceBefore=14,
        spaceAfter=8
    )

    day_title_style = ParagraphStyle(
        'DayHeading',
        parent=styles['Heading2'],
        fontName=font_bold_name,
        fontSize=13,
        leading=16,
        textColor=primary_color,
        spaceBefore=10,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName=font_name,
        fontSize=9.5,
        leading=13.5,
        textColor=text_color,
        spaceAfter=5
    )

    card_label_style = ParagraphStyle(
        'CardLabel',
        parent=body_style,
        fontName=font_bold_name,
        fontSize=10,
        textColor=colors.HexColor("#475569")
    )

    story = []
    
    # Cover / Header Branding
    story.append(Paragraph(dict_labels["report_title"], title_style))
    story.append(Paragraph(f"<b>{dict_labels['report_subtitle']}</b>", ParagraphStyle('SubTitle', fontName=font_bold_name, fontSize=12, leading=14, textColor=colors.HexColor("#64748B"), spaceAfter=15)))
    
    # BMI summary card if bmi is provided
    bmi = data.get("bmi", 0)
    if bmi:
        bmi_text = f"<b>{dict_labels['your_bmi']} {bmi}</b>"
        bmi_table = Table([[Paragraph(bmi_text, ParagraphStyle('BmiText', parent=body_style, fontSize=11, textColor=primary_color))]], colWidths=[504])
        bmi_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F0FDF4")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#BBF7D0")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ]))
        story.append(bmi_table)
        story.append(Spacer(1, 10))
    
    divider = Table([[""]], colWidths=[504])
    divider.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 1.5, primary_color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(divider)
    story.append(Spacer(1, 15))

    # 7-Day Plan details
    plan = data.get("plan", [])
    for idx, day_plan in enumerate(plan):
        day_elements = []
        day_name = day_plan.get("day", f"Day {idx+1}")
        day_elements.append(Paragraph(f"📅 {day_name}", day_title_style))
        
        # Grid content
        # Morning Routine
        morning = day_plan.get("morning", {})
        morning_text = (
            f"<b>{dict_labels['wake_time']}</b> {morning.get('time', 'N/A')}<br/>"
            f"<b>{dict_labels['drink']}</b> {morning.get('drink', 'N/A')}<br/>"
            f"<b>{dict_labels['activity']}</b> {morning.get('activity', 'N/A')}"
        )
        
        # Meals
        meals = day_plan.get("meals", {})
        meals_text = (
            f"<b>{dict_labels['breakfast']}</b> {meals.get('breakfast', 'N/A')}<br/>"
            f"<b>{dict_labels['snack']}</b> {meals.get('snack1', 'N/A')}<br/>"
            f"<b>{dict_labels['lunch']}</b> {meals.get('lunch', 'N/A')}<br/>"
            f"<b>{dict_labels['snack']}</b> {meals.get('snack2', 'N/A')}<br/>"
            f"<b>{dict_labels['dinner']}</b> {meals.get('dinner', 'N/A')}<br/>"
            f"<b>{dict_labels['total_calories']}</b> {meals.get('total_calories', 'N/A')} kcal"
        )
        
        # Exercise
        ex = day_plan.get("exercise", {})
        routine_str = ", ".join(ex.get("routine", []))
        ex_text = (
            f"<b>{dict_labels['type']}</b> {ex.get('type', 'N/A')}<br/>"
            f"<b>{dict_labels['duration']}</b> {ex.get('duration', 'N/A')}<br/>"
            f"<b>{dict_labels['intensity']}</b> {ex.get('intensity', 'N/A')}<br/>"
            f"<b>{dict_labels['routine']}</b> {routine_str or 'N/A'}"
        )
        
        # Wellness
        well = day_plan.get("wellness", {})
        well_text = (
            f"<b>{dict_labels['water_intake']}</b> {well.get('water', 'N/A')}<br/>"
            f"<b>{dict_labels['sleep']}</b> {well.get('sleep', 'N/A')}<br/>"
            f"<b>{dict_labels['tip']}</b> {well.get('tip', 'N/A')}"
        )
        
        table_data = [
            [
                Paragraph(f"<b>{dict_labels['morning_routine']}</b>", card_label_style),
                Paragraph(f"<b>{dict_labels['meals_diet']}</b>", card_label_style)
            ],
            [
                Paragraph(morning_text, body_style),
                Paragraph(meals_text, body_style)
            ],
            [
                Paragraph(f"<b>{dict_labels['exercise_activity']}</b>", card_label_style),
                Paragraph(f"<b>{dict_labels['wellness_sleep']}</b>", card_label_style)
            ],
            [
                Paragraph(ex_text, body_style),
                Paragraph(well_text, body_style)
            ]
        ]
        
        day_table = Table(table_data, colWidths=[246, 246])
        day_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F8FAFC")),
            ('BACKGROUND', (0,2), (-1,2), colors.HexColor("#F8FAFC")),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        day_elements.append(day_table)
        day_elements.append(Spacer(1, 15))
        
        # Keep each day's plan together as a single block so page breaks happen cleanly
        story.append(KeepTogether(day_elements))
        
    # Disclaimer
    story.append(Spacer(1, 10))
    story.append(Paragraph(dict_labels["disclaimer"], ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, textColor=colors.HexColor("#64748B"))))
    
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def generate_health_card_pdf(profile: dict, picture_url: str = None) -> bytes:
    """
    Generate a branded, printable Health Card PDF from the user's health profile.
    Used by POST /api/profile/health-card-pdf
    Args:
        profile: dict with user health data
        picture_url: optional URL to user's profile picture (Google avatar)
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=54, leftMargin=54,
        topMargin=54, bottomMargin=54
    )

    styles = getSampleStyleSheet()
    primary    = colors.HexColor("#1A7A4A")
    danger     = colors.HexColor("#DC2626")
    amber      = colors.HexColor("#D97706")
    slate      = colors.HexColor("#475569")
    light_bg   = colors.HexColor("#F8FAFC")
    border     = colors.HexColor("#E2E8F0")
    green_bg   = colors.HexColor("#F0FDF4")
    green_bdr  = colors.HexColor("#BBF7D0")
    red_bg     = colors.HexColor("#FEF2F2")
    red_bdr    = colors.HexColor("#FCA5A5")

    def _para(text, size=10, color=None, bold=False, leading=14):
        fn = font_bold_name if bold else font_name
        cl = color or colors.HexColor("#1E293B")
        return Paragraph(text, ParagraphStyle(
            f's{size}', parent=styles['Normal'],
            fontName=fn, fontSize=size, leading=leading,
            textColor=cl, spaceAfter=3
        ))

    def _section_header(text):
        tbl = Table([[_para(text, 11, colors.white, bold=True)]], colWidths=[504])
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), primary),
            ('PADDING', (0,0), (-1,-1), 8),
            ('ROUNDEDCORNERS', [4]),
        ]))
        return tbl

    def _row(label, value, val_color=None):
        return [
            _para(label, 9.5, slate, bold=True),
            _para(str(value) if value else "—", 9.5, val_color)
        ]

    def _badges(items, bg, fg):
        if not items:
            return _para("None", 9, slate)
        chips = "  ".join(f"[{i}]" for i in items)
        return _para(chips, 9, fg)

    story = []

    # ── Logo / Title with optional profile picture ──────────────
    header_content = []
    
    # Try to fetch and embed profile picture if URL provided
    profile_img = None
    if picture_url:
        try:
            import requests
            from reportlab.platypus import Image as RLImage
            from PIL import Image as PILImage
            resp = requests.get(picture_url, timeout=3)
            if resp.status_code == 200:
                img_buffer = io.BytesIO(resp.content)
                # Convert to RGB if needed, resize
                pil_img = PILImage.open(img_buffer)
                if pil_img.mode != 'RGB':
                    pil_img = pil_img.convert('RGB')
                pil_img = pil_img.resize((60, 60), PILImage.Resampling.LANCZOS)
                # Save back to buffer
                img_out = io.BytesIO()
                pil_img.save(img_out, format='JPEG')
                img_out.seek(0)
                profile_img = RLImage(img_out, width=60, height=60)
        except Exception as e:
            print(f"[PDF] Could not fetch profile picture: {e}")
    
    # Build header row with picture if available
    if profile_img:
        header_table_data = [
            [profile_img, _para("🏥  MediMitra", 26, primary, bold=True, leading=30)]
        ]
        header_tbl = Table(header_table_data, colWidths=[70, 434])
        header_tbl.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 0),
        ]))
        story.append(header_tbl)
    else:
        story.append(_para("🏥  MediMitra", 26, primary, bold=True, leading=30))
    
    story.append(_para("Personal Health Card", 13, slate, leading=16))
    story.append(_para(
        f"<b>{profile.get('full_name', 'Patient')}</b>",
        18, colors.HexColor("#1E293B"), bold=True, leading=22
    ))
    story.append(_para(
        f"Generated on: {__import__('datetime').date.today().strftime('%d %B %Y')}",
        9, slate
    ))
    story.append(Spacer(1, 8))

    # Divider
    div = Table([[""]], colWidths=[504])
    div.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 2, primary),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(div)
    story.append(Spacer(1, 12))

    # ── SECTION A: Personal Info ──────────────────────────────────
    story.append(_section_header("👤  Personal Information"))
    story.append(Spacer(1, 6))

    # BMI calculation
    bmi_str = "—"
    try:
        h = float(profile.get("height_cm") or 0)
        w = float(profile.get("weight_kg") or 0)
        if h > 0 and w > 0:
            bmi_val = round(w / ((h / 100) ** 2), 1)
            cat = ("Underweight" if bmi_val < 18.5 else
                   "Normal"      if bmi_val < 25   else
                   "Overweight"  if bmi_val < 30   else "Obese")
            bmi_str = f"{bmi_val} ({cat})"
    except Exception:
        pass

    personal_data = [
        _row("Age",          f"{profile.get('age', '—')} years"),
        _row("Gender",       profile.get("gender", "—")),
        _row("Blood Group",  profile.get("blood_group", "—"), danger),
        _row("Height",       f"{profile.get('height_cm', '—')} cm"),
        _row("Weight",       f"{profile.get('weight_kg', '—')} kg"),
        _row("BMI",          bmi_str),
    ]
    personal_tbl = Table(personal_data, colWidths=[160, 344])
    personal_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), light_bg),
        ('GRID',       (0,0), (-1,-1), 0.4, border),
        ('PADDING',    (0,0), (-1,-1), 7),
        ('VALIGN',     (0,0), (-1,-1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [light_bg, colors.white]),
    ]))
    story.append(personal_tbl)
    story.append(Spacer(1, 14))

    # ── SECTION B: Allergies ──────────────────────────────────────
    story.append(_section_header("⚠️  Allergies"))
    story.append(Spacer(1, 6))
    allergies = profile.get("allergies") or []
    allergy_tbl = Table([[_badges(allergies, red_bg, danger)]], colWidths=[504])
    allergy_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), red_bg),
        ('BOX',        (0,0), (-1,-1), 0.5, red_bdr),
        ('PADDING',    (0,0), (-1,-1), 10),
    ]))
    story.append(allergy_tbl)
    story.append(Spacer(1, 14))

    # ── SECTION C: Chronic Conditions ────────────────────────────
    story.append(_section_header("🩺  Chronic Conditions"))
    story.append(Spacer(1, 6))
    conditions = profile.get("chronic_conditions") or []
    cond_tbl = Table([[_badges(conditions, green_bg, primary)]], colWidths=[504])
    cond_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), green_bg),
        ('BOX',        (0,0), (-1,-1), 0.5, green_bdr),
        ('PADDING',    (0,0), (-1,-1), 10),
    ]))
    story.append(cond_tbl)
    story.append(Spacer(1, 14))

    # ── SECTION D: Medications ────────────────────────────────────
    story.append(_section_header("💊  Current Medications"))
    story.append(Spacer(1, 6))
    meds = profile.get("current_medications") or []
    if meds:
        med_rows = [[_para(f"{i+1}.", 9.5, slate, bold=True), _para(m, 9.5)] for i, m in enumerate(meds)]
        med_tbl = Table(med_rows, colWidths=[30, 474])
        med_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), light_bg),
            ('GRID',       (0,0), (-1,-1), 0.4, border),
            ('PADDING',    (0,0), (-1,-1), 6),
        ]))
        story.append(med_tbl)
    else:
        story.append(_para("No current medications recorded.", 9.5, slate))
    story.append(Spacer(1, 14))

    # ── SECTION E: Past Surgeries ────────────────────────────────
    surgeries = profile.get("past_surgeries") or []
    if surgeries:
        story.append(_section_header("🔪  Past Surgeries"))
        story.append(Spacer(1, 6))
        surg_rows = [[_para(f"•  {s}", 9.5)] for s in surgeries]
        surg_tbl = Table(surg_rows, colWidths=[504])
        surg_tbl.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), light_bg),
            ('GRID',       (0,0), (-1,-1), 0.4, border),
            ('PADDING',    (0,0), (-1,-1), 6),
        ]))
        story.append(surg_tbl)
        story.append(Spacer(1, 14))

    # ── SECTION F: Emergency Contact ─────────────────────────────
    story.append(_section_header("🆘  Emergency Contact"))
    story.append(Spacer(1, 6))
    ec_name     = profile.get("emergency_contact_name", "—")
    ec_relation = profile.get("emergency_contact_relation", "—")
    ec_phone    = profile.get("emergency_contact_phone", "—")
    ec_data = [
        _row("Name",         ec_name),
        _row("Relationship", ec_relation),
        _row("Phone",        ec_phone, danger),
    ]
    ec_tbl = Table(ec_data, colWidths=[160, 344])
    ec_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), red_bg),
        ('BOX',        (0,0), (-1,-1), 1.5, danger),
        ('GRID',       (0,0), (-1,-1), 0.4, red_bdr),
        ('PADDING',    (0,0), (-1,-1), 8),
    ]))
    story.append(ec_tbl)
    story.append(Spacer(1, 20))

    # ── Disclaimer ────────────────────────────────────────────────
    disclaimer = Table([[_para(
        "This health card is generated by <b>MediMitra AI Health Platform</b>. "
        "For emergencies call <b>112</b> (National) or <b>108</b> (Free Ambulance). "
        "MediMitra is an AI tool only — not a substitute for professional medical advice.",
        8, slate
    )]], colWidths=[504])
    disclaimer.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), light_bg),
        ('BOX',        (0,0), (-1,-1), 0.5, border),
        ('PADDING',    (0,0), (-1,-1), 10),
    ]))
    story.append(disclaimer)

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
